//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhlBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DhlBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, DHL ProView is a web-based shipment visibility and event notification tool specifically designed to improve tracking for DHL Express account holders. Please refer to your local DHL website to find out if DHL ProView is available in your country. While not available globally right now, it will be available in all countries in the near future..
        /// </summary>
        public static string AccountCustomerMessage {
            get {
                return ResourceManager.GetString("AccountCustomerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This usually occurs if the information we have is insufficient to track the shipment for you. The address may be incorrect and we require clarification or some additional information may be required. The matter can be resolved very quickly by contacting customer service : http://www.dhl.com/en/contact_center/contact_express.html.
        /// </summary>
        public static string ContactDhlMessage {
            get {
                return ResourceManager.GetString("ContactDhlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This status provides an indication of the clearance processing from the destination. Please click in to the Further details (+) to open and see additional information available. This checkpoint allows you to see very early if there is additional information required by customs for clearance..
        /// </summary>
        public static string CustomStatusMessage {
            get {
                return ResourceManager.GetString("CustomStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your shipment failed to arrive, it is important that you contact customer service with an accurate description of the goods and their packaging as soon as possible. Our “found shipment centers” hold on to items that were not properly addressed or that became detached from their packaging. It is possible that they will be able to reunite you with your shipment. If this fails, please contact customer servicecontact customer service to file a report.
        ///Please note that damage to goods in transit is frequentl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DamageClaimMessage {
            get {
                return ResourceManager.GetString("DamageClaimMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pickup and Delivery destinations shown on the DHL Express tracking results are based on the destination of the Service Station location providing that pickup and delivery. Please be assured that your shipment is being delivered to the destination provided by you when you completed the waybill for your shipment(s)..
        /// </summary>
        public static string DifferentTownMessage {
            get {
                return ResourceManager.GetString("DifferentTownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolutely! DHL has unrivalled experience of international shipping. Please click this link http://www.dhl.com/en/contact_center/contact_express.html to contact DHL sales to discuss your needs..
        /// </summary>
        public static string ExportAdviseMessage {
            get {
                return ResourceManager.GetString("ExportAdviseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the (+) an additional level of detail on the status of your shipment will be visible. This further detail can be as simple as confirming the clearance processing is completed, but can also be a more detailed explanation on why the shipment is held in customs and/or additional information required for clearance processing..
        /// </summary>
        public static string FurtherDetailsMessage {
            get {
                return ResourceManager.GetString("FurtherDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to discuss this with the vendor. It depends on the type of commodity you are purchasing, the value of the goods, how the vendor labels them for customs purposes and what country you are importing them into. If customs imposes a charge DHL will pay this in the first instance, however you are advised to pay this, whether or not you accept delivery of the goods..
        /// </summary>
        public static string ImportDutyMessage {
            get {
                return ResourceManager.GetString("ImportDutyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I do not understand your request..
        /// </summary>
        public static string IntentNotFoundMessage {
            get {
                return ResourceManager.GetString("IntentNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There could be various reasons. The DHL Express Waybill for Time Definite shipments is a 10 digit numeric number (e.g. 1234567890, 2345678901), so please recheck the number and try again..
        /// </summary>
        public static string InvalidWaybillMessage {
            get {
                return ResourceManager.GetString("InvalidWaybillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the unlikely event that a Time Definite Delivery misses its scheduled delivery through our fault, you should click http://www.dhl.com/en/contact_center/contact_express.html to contact your local customer service department who will arrange a credit for you..
        /// </summary>
        public static string LateDeliveryMessage {
            get {
                return ResourceManager.GetString("LateDeliveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For shipments that have not yet been delivered, you can sign up for email or SMS/Text message notifications to receive delivery status updates. This saves you time – you don’t have to go online again to track your shipment..
        /// </summary>
        public static string NotificationsSignupMessage {
            get {
                return ResourceManager.GetString("NotificationsSignupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL periodically recycles shipment waybill numbers for operational reasons. Occasionally this results in information being in our systems at the same time for two shipments travelling under the same waybill number. DHL is working hard to eliminate these occurrences however, in the meantime, please be assured that while this information may be confusing, your physical shipment will be heading to its correct destination and be receiving the same careful attention as every other shipment in our network..
        /// </summary>
        public static string NotIntendedMessage {
            get {
                return ResourceManager.GetString("NotIntendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, under certain conditions. We strongly advise you to make a record of your tracking number however, if you have the shipper&apos;s reference number, you can use our online Shipper’s Reference Tracking service..
        /// </summary>
        public static string NoTrackingNumberMessage {
            get {
                return ResourceManager.GetString("NoTrackingNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the size of the door openings on our vans and planes, we ask that a shipment does not exceed 120 cm in dimension. We will be pleased to advise and arrange carriage of any larger items for you. In addition, for the safety of our couriers, we require notification of shipments over 50kg in weight..
        /// </summary>
        public static string PackageSizeMessage {
            get {
                return ResourceManager.GetString("PackageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DHL account is highly recommended if you ship frequently. This offers you negotiated price savings and the opportunity to pay by monthly invoice. Less frequent shippers can pay by cash or credit card..
        /// </summary>
        public static string PaymentMethodsMessage {
            get {
                return ResourceManager.GetString("PaymentMethodsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DHL Tracking page: http://www.dhl.com/en/express/tracking.html can provide up-to-date information on your shipment location..
        /// </summary>
        public static string ShipmentArrivalMessage {
            get {
                return ResourceManager.GetString("ShipmentArrivalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that when purchasing goods via internet sites, some or all of these goods may not originate in your home country. When goods are not sent domestically or within a single customs union, you are liable to pay any inbound duties and taxes which your local Customs authority deems appropriate. Duties and taxes are most typically not included in the price of the goods you purchase online. 
        ///
        ///DHL pays the Customs authority on your behalf any duties and taxes that are due on the goods, when they en [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShippingCostsMessage {
            get {
                return ResourceManager.GetString("ShippingCostsMessage", resourceCulture);
            }
        }
    }
}
